### ISSUE TITLE
Nested objects in Dependencies.kt cannot be referenced from Groovy scripts

### ISSUE THREAD

**Issue by tbsandee** [handstandsam/AndroidDependencyManagement#4]
For some reason, nested objects in Dependencies.kt cannot be referenced from Groovy scripts. For example:

```
object Deps {
    // unfortunately this doesn't work!
    object Kotlin {
        val stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
        val gradle_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    }
```

The error is "No such property: Kotlin for class: Deps". So it looks like it's trying to reference the static inner class as a property of Deps.

See this branch for a complete example:
https://github.com/tbsandee/AndroidDependencyManagement/tree/nestedobjects

Wondering if there is a syntactic change that could allow for this sort of organization, or if we're dealing with a limitation of Groovy?

**Comment by chibatching** [comment]
I found the solution to solve it.
If we put the Deps class into some package. We can reference the inner objects.

```kotlin
package dependencies

object Deps {
    // We can now reference!
    object Kotlin {
        val stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
        val gradle_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    }
```

Just bit annoying, we need import on `build.gradle`. 🙃 

```groovy
import dependencies.Deps

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

dependencies {
    implementation Deps.Kotlin.stdlib
```

**Comment by tbsandee** [comment]
Oh, that's awesome!

**Comment by handstandsam** [comment]
Well done!  Going to mark this as closed since you've figured it out.  Thanks!
